"""Add is_system field to chat_history

Revision ID: 27df666da7cf
Revises: 45e9507bbef3
Create Date: 2025-10-17 01:19:41.270897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27df666da7cf'
down_revision: Union[str, Sequence[str], None] = '45e9507bbef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('is_system', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'is_system')
    # ### end Alembic commands ###