"""Add user_balance table

Revision ID: 45e9507bbef3
Revises: 59276a925d5d
Create Date: 2025-10-16 14:57:35.137724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45e9507bbef3'
down_revision: Union[str, Sequence[str], None] = '59276a925d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_balance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('last_transaction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_balance')
    # ### end Alembic commands ###