"""Add new user fields

Revision ID: 59276a925d5d
Revises: a1d83d69afbf
Create Date: 2025-10-16 13:10:23.823674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59276a925d5d'
down_revision: Union[str, Sequence[str], None] = 'a1d83d69afbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_module', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('consent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('users', 'consent')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'current_module')
    # ### end Alembic commands ###